version: "3"
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: base_db
      POSTGRES_USER: base_user
      POSTGRES_PASSWORD: base_password
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: base_user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: base_password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data: {}
  pgadmin_data: {}
